<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // $this->call(UsersTableSeeder::class);
        $now = \Carbon\Carbon::now();
        
        $regiones = [
            [1,'Arica y Parinacota','XV'],
            [2,'Tarapacá','I'],
            [3,'Antofagasta','II'],
            [4,'Atacama','III'],
            [5,'Coquimbo','IV'],
            [6,'Valparaiso','V'],
            [7,'Metropolitana de Santiago','RM'],
            [8,'Libertador General Bernardo O\'Higgins','VI'],
            [9,'Maule','VII'],
            [10,'Biobío','VIII'],
            [11,'La Araucanía','IX'],
            [12,'Los Ríos','XIV'],
            [13,'Los Lagos','X'],
            [14,'Aisén del General Carlos Ibáñez del Campo','XI'],
            [15,'Magallanes y de la Antártica Chilena','XII'],
            [16,'Ñuble','XVI'],
        ];
        $regiones = array_map(function($region) use ($now) {
           return [
               'id' => $region[0],
               'region' => $region[1],
               'ordinal' => $region[2],
               'updated_at' => $now,
               'created_at' => $now,
           ];
        }, $regiones);
        \DB::table('region')->insert($regiones);

        $comunas = [
            [1,'Arica',1],
            [2,'Camarones',1],
            [3,'General Lagos',1],
            [4,'Putre',1],
            [5,'Alto Hospicio',2],
            [6,'Iquique',2],
            [7,'Camiña',2],
            [8,'Colchane',2],
            [9,'Huara',2],
            [10,'Pica',2],
            [11,'Pozo Almonte',2],
            [12,'Antofagasta',3],
            [13,'Mejillones',3],
            [14,'Sierra Gorda',3],
            [15,'Taltal',3],
            [16,'Calama',3],
            [17,'Ollague',3],
            [18,'San Pedro de Atacama',3],
            [19,'María Elena',3],
            [20,'Tocopilla',3],
            [21,'Chañaral',4],
            [22,'Diego de Almagro',4],
            [23,'Caldera',4],
            [24,'Copiapó',4],
            [25,'Tierra Amarilla',4],
            [26,'Alto del Carmen',4],
            [27,'Freirina',4],
            [28,'Huasco',4],
            [29,'Vallenar',4],
            [30,'Canela',5],
            [31,'Illapel',5],
            [32,'Los Vilos',5],
            [33,'Salamanca',5],
            [34,'Andacollo',5],
            [35,'Coquimbo',5],
            [36,'La Higuera',5],
            [37,'La Serena',5],
            [38,'Paihuaco',5],
            [39,'Vicuña',5],
            [40,'Combarbalá',5],
            [41,'Monte Patria',5],
            [42,'Ovalle',5],
            [43,'Punitaqui',5],
            [44,'Río Hurtado',5],
            [45,'Isla de Pascua',6],
            [46,'Calle Larga',6],
            [47,'Los Andes',6],
            [48,'Rinconada',6],
            [49,'San Esteban',6],
            [50,'La Ligua',6],
            [51,'Papudo',6],
            [52,'Petorca',6],
            [53,'Zapallar',6],
            [54,'Hijuelas',6],
            [55,'La Calera',6],
            [56,'La Cruz',6],
            [57,'Limache',6],
            [58,'Nogales',6],
            [59,'Olmué',6],
            [60,'Quillota',6],
            [61,'Algarrobo',6],
            [62,'Cartagena',6],
            [63,'El Quisco',6],
            [64,'El Tabo',6],
            [65,'San Antonio',6],
            [66,'Santo Domingo',6],
            [67,'Catemu',6],
            [68,'Llaillay',6],
            [69,'Panquehue',6],
            [70,'Putaendo',6],
            [71,'San Felipe',6],
            [72,'Santa María',6],
            [73,'Casablanca',6],
            [74,'Concón',6],
            [75,'Juan Fernández',6],
            [76,'Puchuncaví',6],
            [77,'Quilpué',6],
            [78,'Quintero',6],
            [79,'Valparaíso',6],
            [80,'Villa Alemana',6],
            [81,'Viña del Mar',6],
            [82,'Colina',7],
            [83,'Lampa',7],
            [84,'Tiltil',7],
            [85,'Pirque',7],
            [86,'Puente Alto',7],
            [87,'San José de Maipo',7],
            [88,'Buin',7],
            [89,'Calera de Tango',7],
            [90,'Paine',7],
            [91,'San Bernardo',7],
            [92,'Alhué',7],
            [93,'Curacaví',7],
            [94,'María Pinto',7],
            [95,'Melipilla',7],
            [96,'San Pedro',7],
            [97,'Cerrillos',7],
            [98,'Cerro Navia',7],
            [99,'Conchalí',7],
            [100,'El Bosque',7],
            [101,'Estación Central',7],
            [102,'Huechuraba',7],
            [103,'Independencia',7],
            [104,'La Cisterna',7],
            [105,'La Granja',7],
            [106,'La Florida',7],
            [107,'La Pintana',7],
            [108,'La Reina',7],
            [109,'Las Condes',7],
            [110,'Lo Barnechea',7],
            [111,'Lo Espejo',7],
            [112,'Lo Prado',7],
            [113,'Macul',7],
            [114,'Maipú',7],
            [115,'Ñuñoa',7],
            [116,'Pedro Aguirre Cerda',7],
            [117,'Peñalolén',7],
            [118,'Providencia',7],
            [119,'Pudahuel',7],
            [120,'Quilicura',7],
            [121,'Quinta Normal',7],
            [122,'Recoleta',7],
            [123,'Renca',7],
            [124,'San Miguel',7],
            [125,'San Joaquín',7],
            [126,'San Ramón',7],
            [127,'Santiago',7],
            [128,'Vitacura',7],
            [129,'El Monte',7],
            [130,'Isla de Maipo',7],
            [131,'Padre Hurtado',7],
            [132,'Peñaflor',7],
            [133,'Talagante',7],
            [134,'Codegua',8],
            [135,'Coínco',8],
            [136,'Coltauco',8],
            [137,'Doñihue',8],
            [138,'Graneros',8],
            [139,'Las Cabras',8],
            [140,'Machalí',8],
            [141,'Malloa',8],
            [142,'Mostazal',8],
            [143,'Olivar',8],
            [144,'Peumo',8],
            [145,'Pichidegua',8],
            [146,'Quinta de Tilcoco',8],
            [147,'Rancagua',8],
            [148,'Rengo',8],
            [149,'Requínoa',8],
            [150,'San Vicente de Tagua Tagua',8],
            [151,'La Estrella',8],
            [152,'Litueche',8],
            [153,'Marchihue',8],
            [154,'Navidad',8],
            [155,'Peredones',8],
            [156,'Pichilemu',8],
            [157,'Chépica',8],
            [158,'Chimbarongo',8],
            [159,'Lolol',8],
            [160,'Nancagua',8],
            [161,'Palmilla',8],
            [162,'Peralillo',8],
            [163,'Placilla',8],
            [164,'Pumanque',8],
            [165,'San Fernando',8],
            [166,'Santa Cruz',8],
            [167,'Cauquenes',9],
            [168,'Chanco',9],
            [169,'Pelluhue',9],
            [170,'Curicó',9],
            [171,'Hualañé',9],
            [172,'Licantén',9],
            [173,'Molina',9],
            [174,'Rauco',9],
            [175,'Romeral',9],
            [176,'Sagrada Familia',9],
            [177,'Teno',9],
            [178,'Vichuquén',9],
            [179,'Colbún',9],
            [180,'Linares',9],
            [181,'Longaví',9],
            [182,'Parral',9],
            [183,'Retiro',9],
            [184,'San Javier',9],
            [185,'Villa Alegre',9],
            [186,'Yerbas Buenas',9],
            [187,'Constitución',9],
            [188,'Curepto',9],
            [189,'Empedrado',9],
            [190,'Maule',9],
            [191,'Pelarco',9],
            [192,'Pencahue',9],
            [193,'Río Claro',9],
            [194,'San Clemente',9],
            [195,'San Rafael',9],
            [196,'Talca',9],
            [197,'Arauco',10],
            [198,'Cañete',10],
            [199,'Contulmo',10],
            [200,'Curanilahue',10],
            [201,'Lebu',10],
            [202,'Los Álamos',10],
            [203,'Tirúa',10],
            [204,'Alto Biobío',10],
            [205,'Antuco',10],
            [206,'Cabrero',10],
            [207,'Laja',10],
            [208,'Los Ángeles',10],
            [209,'Mulchén',10],
            [210,'Nacimiento',10],
            [211,'Negrete',10],
            [212,'Quilaco',10],
            [213,'Quilleco',10],
            [214,'San Rosendo',10],
            [215,'Santa Bárbara',10],
            [216,'Tucapel',10],
            [217,'Yumbel',10],
            [218,'Chiguayante',10],
            [219,'Concepción',10],
            [220,'Coronel',10],
            [221,'Florida',10],
            [222,'Hualpén',10],
            [223,'Hualqui',10],
            [224,'Lota',10],
            [225,'Penco',10],
            [226,'San Pedro de La Paz',10],
            [227,'Santa Juana',10],
            [228,'Talcahuano',10],
            [229,'Tomé',10],
            [230,'Bulnes',16],
            [231,'Chillán',16],
            [232,'Chillán Viejo',16],
            [233,'Cobquecura',16],
            [234,'Coelemu',16],
            [235,'Coihueco',16],
            [236,'El Carmen',16],
            [237,'Ninhue',16],
            [238,'Ñiquen',16],
            [239,'Pemuco',16],
            [240,'Pinto',16],
            [241,'Portezuelo',16],
            [242,'Quillón',16],
            [243,'Quirihue',16],
            [244,'Ránquil',16],
            [245,'San Carlos',16],
            [246,'San Fabián',16],
            [247,'San Ignacio',16],
            [248,'San Nicolás',16],
            [249,'Treguaco',16],
            [250,'Yungay',16],
            [251,'Carahue',11],
            [252,'Cholchol',11],
            [253,'Cunco',11],
            [254,'Curarrehue',11],
            [255,'Freire',11],
            [256,'Galvarino',11],
            [257,'Gorbea',11],
            [258,'Lautaro',11],
            [259,'Loncoche',11],
            [260,'Melipeuco',11],
            [261,'Nueva Imperial',11],
            [262,'Padre Las Casas',11],
            [263,'Perquenco',11],
            [264,'Pitrufquén',11],
            [265,'Pucón',11],
            [266,'Saavedra',11],
            [267,'Temuco',11],
            [268,'Teodoro Schmidt',11],
            [269,'Toltén',11],
            [270,'Vilcún',11],
            [271,'Villarrica',11],
            [272,'Angol',11],
            [273,'Collipulli',11],
            [274,'Curacautín',11],
            [275,'Ercilla',11],
            [276,'Lonquimay',11],
            [277,'Los Sauces',11],
            [278,'Lumaco',11],
            [279,'Purén',11],
            [280,'Renaico',11],
            [281,'Traiguén',11],
            [282,'Victoria',11],
            [283,'Corral',12],
            [284,'Lanco',12],
            [285,'Los Lagos',12],
            [286,'Máfil',12],
            [287,'Mariquina',12],
            [288,'Paillaco',12],
            [289,'Panguipulli',12],
            [290,'Valdivia',12],
            [291,'Futrono',12],
            [292,'La Unión',12],
            [293,'Lago Ranco',12],
            [294,'Río Bueno',12],
            [295,'Ancud',13],
            [296,'Castro',13],
            [297,'Chonchi',13],
            [298,'Curaco de Vélez',13],
            [299,'Dalcahue',13],
            [300,'Puqueldón',13],
            [301,'Queilén',13],
            [302,'Quemchi',13],
            [303,'Quellón',13],
            [304,'Quinchao',13],
            [305,'Calbuco',13],
            [306,'Cochamó',13],
            [307,'Fresia',13],
            [308,'Frutillar',13],
            [309,'Llanquihue',13],
            [310,'Los Muermos',13],
            [311,'Maullín',13],
            [312,'Puerto Montt',13],
            [313,'Puerto Varas',13],
            [314,'Osorno',13],
            [315,'Puero Octay',13],
            [316,'Purranque',13],
            [317,'Puyehue',13],
            [318,'Río Negro',13],
            [319,'San Juan de la Costa',13],
            [320,'San Pablo',13],
            [321,'Chaitén',13],
            [322,'Futaleufú',13],
            [323,'Hualaihué',13],
            [324,'Palena',13],
            [325,'Aisén',14],
            [326,'Cisnes',14],
            [327,'Guaitecas',14],
            [328,'Cochrane',14],
            [329,'O\'higgins',14],
            [330,'Tortel',14],
            [331,'Coihaique',14],
            [332,'Lago Verde',14],
            [333,'Chile Chico',14],
            [334,'Río Ibáñez',14],
            [335,'Antártica',15],
            [336,'Cabo de Hornos',15],
            [337,'Laguna Blanca',15],
            [338,'Punta Arenas',15],
            [339,'Río Verde',15],
            [340,'San Gregorio',15],
            [341,'Porvenir',15],
            [342,'Primavera',15],
            [343,'Timaukel',15],
            [344,'Natales',15],
            [345,'Torres del Paine',15],
            [346,'Cabildo',6]
        ];
        $comunas = array_map(function($comuna) use ($now) {
            return [
                'id' => $comuna[0],
                'comuna' => $comuna[1],
                'region_id' => $comuna[2],
                'updated_at' => $now,
                'created_at' => $now,
            ];
        }, $comunas);
        //App\Commune::insert($data); // Eloquent approach
        \DB::table('comuna')->insert($comunas); // Query Builder approach

        $casas = [
            [1,'P. Universidad Católica','universidad'],
            [2,'P. Univ. Católica de Valparaíso','universidad'],
            [3,'Academica de Humanismo Cristiano','universidad'],
            [4,'Universidad Adolfo Ibáñez','universidad'],
            [5,'Universidad Adventista de Chile','universidad'],
            [6,'Universidad Alberto Hurtado','universidad'],
            [7,'Universidad Andrés Bello','universidad'],
            [8,'Universidad Arturo Prat','universidad'],
            [9,'Universidad Austral','universidad'],
            [10,'Universidad Autónoma','universidad'],
            [11,'Universidad Bernardo O\'Higgins','universidad'],
            [12,'Univ. Católica Silva Henríquez','universidad'],
            [13,'Univ. Católica de la Santísima Concep.','universidad'],
            [14,'Universidad Católica de Temuco','universidad'],
            [15,'Universidad Católica del Maule','universidad'],
            [16,'Universidad Católica del Norte','universidad'],
            [17,'Universidad Central de Chile','universidad'],
            [18,'Universidad de Antofagasta','universidad'],
            [19,'Universidad de Atacama','universidad'],
            [20,'Universidad de Chile','universidad'],
            [21,'Universidad de Concepción','universidad'],
            [22,'Universidad de La Frontera','universidad'],
            [23,'Universidad de La Serena','universidad'],
            [24,'Universidad de Las Américas','universidad'],
            [25,'Universidad de Los Andes','universidad'],
            [26,'Universidad de Los Lagos','universidad'],
            [27,'Universidad de Magallanes','universidad'],
            [28,'Universidad de Playa Ancha de Ciencias de la Educ.','universidad'],
            [29,'Universidad de Santiago de Chile','universidad'],
            [30,'Universidad de Talca','universidad'],
            [31,'Universidad de Tarapacá','universidad'],
            [32,'Universidad de Valparaíso','universidad'],
            [33,'Universidad de Viña del Mar','universidad'],
            [34,'Universidad del Bío-Bío','universidad'],
            [35,'Universidad del Desarrollo','universidad'],
            [36,'Universidad del Pacífico','universidad'],
            [37,'Universidad Diego Portales','universidad'],
            [38,'Universidad Finis Terrae','universidad'],
            [39,'Univ. Iberoamericana de Ciencias y Tecnología Unicit','universidad'],
            [40,'Universidad San Sebastián','universidad'],
            [41,'Univ. Metropolitana de Ciencias de la Educación','universidad'],
            [42,'Universidad Técnico Federico Santa María','universidad'],
            [43,'Universidad Tecnológica de Chile Inacap','universidad'],
            [44,'Universidad Tecnológica Metropolitana','universidad'],
            [45,'Universidad Santo Tomás','universidad'],
            [46,'Universidad Mayor','universidad'],
            [47,'Universidad Gabriela Mistral','universidad'],
            [48,'Instituto Profesional AIEP','ip'],
            [49,'Instituto Profesional Arcos','ip'],
            [50,'Instituto Profesional de Chile','ip'],
            [51,'Instituto Profesional DUOC UC','ip'],
            [52,'Instituto Profesional Guillermo Subercaseaux','ip'],
            [53,'Instituto Profesional Inacap','ip'],
            [54,'Instituto Profesional La Araucana','ip'],
            [55,'Instituto Profesional Santo Tomás','ip'],
            [56,'Instituto Profesional Virginio Gómez','ip'],
            [57,'Instituto Profesional Escuela Moderna de Música','ip'],
            [58,'Instituto Prof. Esc. de Contadores de Chile','ip'],
            [59,'Instituto Profesional Carlos Casanueva','ip'],
            [60,'Instituto Profesional Esucomex','ip'],
            [61,'Instituto Nacional del Fútbol, Deportes y Act. Física','ip'],
            [62,'Instituto Profesional Agrario Adolfo Matthei','ip'],
            [63,'Instituto Profesional Ciisa','ip'],
            [64,'Instituto Profesional Galdámez IPG','ip'],
            [65,'CFT Ceduc-UCN','cft'],
            [66,'CFT del Medio Ambiente IDMA','cft'],
            [67,'CFT Duoc UC','cft'],
            [68,'CFT Inacap','cft'],
            [69,'CFT Instituto Tecnológico de Chile','cft'],
            [70,'CFT Lota Arauco','cft'],
            [71,'CFT San Agustín de Talca','cft'],
            [72,'CFT Santo Tomás','cft'],
            [73,'CFT Tarapacá','cft'],
            [74,'CFT Cámara de Comercio de Santiago','cft'],
            [75,'CFT ENAC','cft'],
            [76,'CFT Ucevalpo','cft'],
            [77,'CFT Proandes','cft'],
            [78,'CFT Juan Bohon','cft'],
            [79,'CFT Teodoro Wickel Klüwen','cft'],
        ];
        $casas = array_map(function($casa) use ($now) {
           return [
               'id' => $casa[0],
               'casa' => $casa[1],
               'tipo' => $casa[2],
               'updated_at' => $now,
               'created_at' => $now,
           ];
        }, $casas);
        \DB::table('casas')->insert($casas);

        $profesiones = [
            [1, 'Abogado'],
            [2, 'Abogado Experto'],
            [3, 'Abogado Senior'],
            [4, 'Actor teatral'],
            [5, 'Administración Pública'],
            [6, 'Administración Turística y Hotelera'],
            [7, 'Administrador Ingenieria de Sistemas de Proyecto'],
            [8, 'Administrador Bases Datos'],
            [9, 'Administrador de Backup'],
            [10, 'Administrador de Contratos'],
            [11, 'Administrador de Servicios'],
            [12, 'Administrador de Servidores'],
            [13, 'Administrador de Sistemas'],
            [14, 'Administrador de Sistemas de Operacion'],
            [15, 'Administrador de Sistemas Microsoft'],
            [16, 'Administrador de Sistemas Middlaware'],
            [17, 'Administrador de Sistemas SAP'],
            [18, 'Administrador de Sistemas SAP de Operacion'],
            [19, 'Administrador de Sistemas Sap Senior'],
            [20, 'Administrador de Sistemas Tools'],
            [21, 'Administrador de Sistemas Unix'],
            [22, 'Administrador Ingenieria De Sistemas'],
            [23, 'Administrador Publico'],
            [24, 'Administrador Sistemas Middleware'],
            [25, 'Administrativo'],
            [26, 'Administrativo Contable'],
            [27, 'Administrativo de Bodega'],
            [28, 'Administrativo de Cobranzas Corporativo'],
            [29, 'Administrativo de Cobranzas Empresas'],
            [30, 'Administrativo de Soporte'],
            [31, 'Administrativo Soporte Cta. Cte. Sap'],
            [32, 'Administrativo Tesorería'],
            [33, 'Agente Mesa de Ayuda'],
            [34, 'Agente Reclamos Back'],
            [35, 'Agente Reclamos Subtel Sernac'],
            [36, 'Agronomo'],
            [37, 'Analista Incentivos y Comisiones'],
            [38, 'Analista Planificacion Ventas'],
            [39, 'Analista Administracion Financiera'],
            [40, 'Analista Alianza'],
            [41, 'Analista Calidad de Servicio'],
            [42, 'Analista Cobranza Canal Indirecto'],
            [43, 'Analista Cobranza Ex Clientes'],
            [44, 'Analista Comercio Exterior'],
            [45, 'Analista Comisiones'],
            [46, 'Analista Compras Técnicas'],
            [47, 'Analista Comunicación Canales'],
            [48, 'Analista Contable'],
            [49, 'Analista Control Cuenta Corriente'],
            [50, 'Analista Control de Facturación Empresas'],
            [51, 'Analista Control de Facturación Personas'],
            [52, 'Analista Control de Gestion'],
            [53, 'Analista Control de Gestion Comercial'],
            [54, 'Analista Control de Gestion Y Soporte'],
            [55, 'Analista Control Fact. Terceros'],
            [56, 'Analista Control Procesos'],
            [57, 'Analista Cuenta Corriente'],
            [58, 'Analista Customer Value Management'],
            [59, 'Analista CVM Gestion Canales'],
            [60, 'Analista de Control de Gestion Senior'],
            [61, 'Analista de Desarrollo'],
            [62, 'Analista De Gestion'],
            [63, 'Analista de Gestion Comercial'],
            [64, 'Analista de Gestion de Cositing y Zonas Saturadas'],
            [65, 'Analista de Gestion Operacional'],
            [66, 'Analista de Inteligencia Inmobiliaria'],
            [67, 'Analista de Marketing'],
            [68, 'Analista de Negocio'],
            [69, 'Analista de Proyectos Senior'],
            [70, 'Analista de Riesgo Operacional'],
            [71, 'Analista de Tesoreria'],
            [72, 'Analista Evaluacion'],
            [73, 'Analista Evaluacion Economica Senior'],
            [74, 'Analista Facturacion Prepago'],
            [75, 'Analista Fidelizacion'],
            [76, 'Analista Formacion'],
            [77, 'Analista Gestión'],
            [78, 'Analista Gestion Back'],
            [79, 'Analista Gestion Comercial Senior'],
            [80, 'Analista Gestion de Demanda'],
            [81, 'Analista Gestion de Informacion'],
            [82, 'Analista Gestión De La Información'],
            [83, 'Analista Gestion IVR'],
            [84, 'Analista Gestion Post Venta Terminales'],
            [85, 'Analista Imagen'],
            [86, 'Analista Inteligencia Segmento'],
            [87, 'Analista Inventario'],
            [88, 'Analista Logistica'],
            [89, 'Analista Marketing'],
            [90, 'Analista Marketing Online'],
            [91, 'Analista Marketing Vas'],
            [92, 'Analista Medios'],
            [93, 'Analista Mercado Terminales Suscripcion'],
            [94, 'Analista Modelo CVM'],
            [95, 'Analista Modelos de Riesgo'],
            [96, 'Analista Negocios Senior'],
            [97, 'Analista Online'],
            [98, 'Analista Operaciones Sac'],
            [99, 'Analista Optimizacion y Reclamos'],
            [100, 'Analista Planif y Control De Gestion'],
            [101, 'Analista Planificacion Capacidades'],
            [102, 'Analista Planificacion Comercial'],
            [103, 'Analista Planificacion De Mercado'],
            [104, 'Analista Planificacion Sac'],
            [105, 'Analista Planificacion Ventas'],
            [106, 'Analista Planificacion Y Control De Gestion Senior'],
            [107, 'Analista Plataformas Comerciales'],
            [108, 'Analista Procesos y Riesgo'],
            [109, 'Analista Relaciones Con Inversionistas Senior'],
            [110, 'Analista Riesgo Personas'],
            [111, 'Analista Senior Business Intelligence'],
            [112, 'Analista Senior Calidad y Experiencia'],
            [113, 'Analista Senior de Incidentes'],
            [114, 'Analista Senior de TV'],
            [115, 'Analista Senior E-Commerce'],
            [116, 'Analista Senior Estrategia Canales'],
            [117, 'Analista Senior Online'],
            [118, 'Analista Soporte Comercial Senior'],
            [119, 'Analista Soporte Procesos'],
            [120, 'Analista Tendencia E Innovacion'],
            [121, 'Analista Terminales Masivos'],
            [122, 'Antropologo'],
            [123, 'Arquitecto'],
            [124, 'Arquitecto Junior'],
            [125, 'Arquitecto Plataformas Vas'],
            [126, 'Asistente Administración Inmobiliaria'],
            [127, 'Asistente Administrativo'],
            [128, 'Asistente Comercial'],
            [129, 'Asistente Comercio Exterior'],
            [130, 'Asistente Compras'],
            [131, 'Asistente Contable'],
            [132, 'Asistente Contable Cuentas Corrientes'],
            [133, 'Asistente Control De Facturacion Empresas'],
            [134, 'Asistente Control De Gestión'],
            [135, 'Asistente Control Facturacion Indirecta Tercero'],
            [136, 'Asistente Control Presupuesto y Contrato'],
            [137, 'Asistente Control Proceso'],
            [138, 'Asistente de Facturacion Administrativa Personas'],
            [139, 'Asistente Ejecutiva'],
            [140, 'Asistente Formacion'],
            [141, 'Asistente Gestion De Stocks'],
            [142, 'Asistente Gestion Reclamos Facturacion'],
            [143, 'Asistente Gestion Reclamos Gerencia'],
            [144, 'Asistente Inventario'],
            [145, 'Asistente Logistica'],
            [146, 'Asistente Operaciones Externas'],
            [147, 'Asistente Operaciones Remotas'],
            [148, 'Asistente Plataformas de Atencion'],
            [149, 'Asistente Programacion y Control'],
            [150, 'Asistente Proyectos'],
            [151, 'Asistente Recaudación Interna'],
            [152, 'Asistente Requerimientos Judiciales'],
            [153, 'Asistente Senior Control de Proyectos'],
            [154, 'Asistente Servicios Generales'],
            [155, 'Asistente Soporte Administrativo'],
            [156, 'Asistente Soporte Canales'],
            [157, 'Asistente Soporte Cobranza'],
            [158, 'Asistente Soporte Servicio'],
            [159, 'Asistente Tecnico'],
            [160, 'Asistente Tecnico Gestion Comercial'],
            [161, 'Asistente Tecnico Servicio al Cliente'],
            [162, 'Auditor Interno'],
            [163, 'Auditor Interno Operacional'],
            [164, 'Auditor Senior'],
            [165, 'Back Soluciones Postventas'],
            [166, 'Bibliotecaria(o)'],
            [167, 'Biologo(a) Marina y Ecología Marina'],
            [168, 'Bioquímico'],
            [169, 'Cajero Comercial'],
            [170, 'Category Manager Suscripción Voz'],
            [171, 'Chofer Gerencia General'],
            [172, 'Cientista Politico'],
            [173, 'Comercial'],
            [174, 'Comunicador Audiovisual y/o Multimedia'],
            [175, 'Constructor Civil'],
            [176, 'Consultor Tecnologico'],
            [177, 'Consultor Tecnologico Senior'],
            [178, 'Contador Auditor'],
            [179, 'Contador Auditor Senior'],
            [180, 'Controlador(A) De Trafico'],
            [181, 'Coordinador (A) Front Post Venta'],
            [182, 'Coordinador Administracion De Contratos'],
            [183, 'Coordinador Aplicaciones Comerciales'],
            [184, 'Coordinador Aseguramiento de Formacion y Calidad'],
            [185, 'Coordinador Back Subtel-Sernac'],
            [186, 'Coordinador Calidad de Servicio'],
            [187, 'Coordinador Campañas y Gestión De Bases'],
            [188, 'Coordinador Canales Masivos'],
            [189, 'Coordinador Club Fidelizacion'],
            [190, 'Coordinador Cobranza'],
            [191, 'Coordinador Comunicaciones y RRII'],
            [192, 'Coordinador Configuracion Comercial'],
            [193, 'Coordinador Configuracion Tecnica'],
            [194, 'Coordinador Control de Gestion'],
            [195, 'Coordinador Control Ingreso De Neg Y Com'],
            [196, 'Coordinador de Desarrollo y Gestion Inmobiliaria'],
            [197, 'Coordinador de Gestion Calidad'],
            [198, 'Coordinador de Marketing Digital'],
            [199, 'Coordinador de Plataforma Externas'],
            [200, 'Coordinador de Proyecto'],
            [201, 'Coordinador de Proyectos'],
            [202, 'Coordinador de Proyectos Corporativos e Inbuilding'],
            [203, 'Coordinador de Terreno'],
            [204, 'Coordinador Desarrollo de Plataformas'],
            [205, 'Coordinador Distribución Personas'],
            [206, 'Coordinador Estrategia Atencion y Gestion Comercial'],
            [207, 'Coordinador Estrategia Canales'],
            [208, 'Coordinador Facturación Electrónica'],
            [209, 'Coordinador Fraude Comercial'],
            [210, 'Coordinador Gestion de Brechas'],
            [211, 'Coordinador Gestión De Calidad Empresas'],
            [212, 'Coordinador Gestión De Calidad Personas'],
            [213, 'Coordinador Gestion Performance'],
            [214, 'Coordinador Implementación De Proyectos'],
            [215, 'Coordinador Implementacion Productos y Servicios'],
            [216, 'Coordinador Implementación Proyectos Empresas'],
            [217, 'Coordinador Mejora Operacional'],
            [218, 'Coordinador Operacion'],
            [219, 'Coordinador Operacion IVR y USSD'],
            [220, 'Coordinador Optimizacion y Reclamos'],
            [221, 'Coordinador Plataformas Comerciales'],
            [222, 'Coordinador Plataformas De Atención'],
            [223, 'Coordinador Soporte Canales'],
            [224, 'Coordinador(A) de Roaming'],
            [225, 'Coordinador(A) Plataforma Externas Pyme'],
            [226, 'Customer Value Manager Grandes Empresas'],
            [227, 'Dibujante Proyectista Cad'],
            [228, 'Director Cuenta Segmento Corporaciones'],
            [229, 'Director de Cuenta Segmento Personas'],
            [230, 'Director de Cuentas Mesa De Trafico'],
            [231, 'Director de Negocios'],
            [232, 'Director de Negocios Móviles'],
            [233, 'Director de Negocios Regional'],
            [234, 'Director de Operacion'],
            [235, 'Director de Proyectos'],
            [236, 'Director de Relaciones Con Inversionistas'],
            [237, 'Director de Servicios'],
            [238, 'Director de Ventas Mayoristas'],
            [239, 'Director Desarrollo Grandes Cuentas Negocio Fijo'],
            [240, 'Director Grandes Cuentas Negocio Fijo'],
            [241, 'Director Grandes Cuentas Negocio Movil'],
            [242, 'Director Integracion Servicios TELCO'],
            [243, 'Director Integral De Servicio Al Cliente'],
            [244, 'Director Integral de Servicios al Cliente Regional'],
            [245, 'Director Integral Servicio Al Cliente Senior'],
            [246, 'Diseñador de Vestuario'],
            [247, 'Diseñador de ambientes'],
            [248, 'Diseñador Gráfico'],
            [249, 'Diseñador Industrial'],
            [250, 'Diseñador web'],
            [251, 'Diseño'],
            [252, 'Editor Contenido Online'],
            [253, 'Ejecutiva Asistencia Gerencia'],
            [254, 'Ejecutivo De Ventas Desarrollo'],
            [255, 'Ejecutivo (A) Cace'],
            [256, 'Ejecutivo (A) Soporte Preferencial'],
            [257, 'Ejecutivo Atencion Comercial'],
            [258, 'Ejecutivo Atencion Empresas'],
            [259, 'Ejecutivo Atencion Grandes Cuentas'],
            [260, 'Ejecutivo Atencion Pref. Empresa Corp'],
            [261, 'Ejecutivo Atencion Preferencial'],
            [262, 'Ejecutivo Atencion Preferencial Empresas'],
            [263, 'Ejecutivo Atencion Pyme'],
            [264, 'Ejecutivo Cap.Emp. Negocio Fijo y Movil'],
            [265, 'Ejecutivo Captura Empresas Negocio Fijo'],
            [266, 'Ejecutivo Captura Empresas Negocio Movil'],
            [267, 'Ejecutivo Comercial'],
            [268, 'Ejecutivo Compras'],
            [269, 'Ejecutivo Compras Tecnicas'],
            [270, 'Ejecutivo de Servicio al Cliente Senior'],
            [271, 'Ejecutivo Desarrollo Empresa Negocio Fijo'],
            [272, 'Ejecutivo Desarrollo Empresa Negocio Fijo Y Movil'],
            [273, 'Ejecutivo Desarrollo Empresas Negocio Movil'],
            [274, 'Ejecutivo Desarrollo Pyme Negocio Fijo'],
            [275, 'Ejecutivo Desarrollo Pyme Negocio Movil'],
            [276, 'Ejecutivo Gestion Comercial'],
            [277, 'Ejecutivo Salon'],
            [278, 'Ejecutivo Servicio Al Cliente'],
            [279, 'Ejecutivo Venta Y Desarrollo'],
            [280, 'Ejecutivo Visa'],
            [281, 'Ejecutivo(A) Captura Pyme Negocio Fijo'],
            [282, 'Ejecutivo(A) Captura Pyme Negocio Movil'],
            [283, 'Ejecutivo(A) Desarrollo Pyme Negocio Fijo y Movil'],
            [284, 'Enfermera'],
            [285, 'Especialista Arquitectura y Tramitaciones Regulatorias'],
            [286, 'Especialista de RRPP'],
            [287, 'Especialista en Rse'],
            [288, 'Especialista Operación de Servicio'],
            [289, 'Especialista Redes Datos'],
            [290, 'Especialista Redes De Transporte'],
            [291, 'Especialista Redes Ran'],
            [292, 'Especialista Redes Satelitales'],
            [293, 'Especialista Ti'],
            [294, 'Especilista Cloud'],
            [295, 'Estudiante de Derecho'],
            [296, 'Explotador de Sistemas'],
            [297, 'Farmacéutico'],
            [298, 'Fisioterapeuta'],
            [299, 'Fonoaudiologo(a)'],
            [300, 'Geografo'],
            [301, 'Geología'],
            [302, 'Gerente de Dpto. Control de Gestion'],
            [303, 'Gerente de Negocios'],
            [304, 'Gerente de Negocios Zona Oriente Rm'],
            [305, 'Gerente de Negocios Zonal'],
            [306, 'Gerente de Planificacion y Gestion'],
            [307, 'Gerente de Servicio y Experiencia de Cliente'],
            [308, 'Gerente de Servicios'],
            [309, 'Gerente Departamento Contabilidad'],
            [310, 'Gerente Departamento I-Factory'],
            [311, 'Gerente Departamento Infraestructura'],
            [312, 'Gerente Departamento Inteligencia Operacional'],
            [313, 'Gerente Departamento Legal'],
            [314, 'Gerente Departamento Marketing Y Productos'],
            [315, 'Gerente Departamento O&M De Servicio Telco'],
            [316, 'Gerente Departamento Operacion Ventas'],
            [317, 'Gerente Departamento Planificacion Y Gestion'],
            [318, 'Gerente Depto Canales Grandes Tiendas y Masivos'],
            [319, 'Gerente Depto De Innovacion'],
            [320, 'Gerente Depto Eval Economica Y Gestion Invers'],
            [321, 'Gerente Depto Gestion de Proyectos In Building'],
            [322, 'Gerente Depto Mercado Mayorista'],
            [323, 'Gerente Depto Supply Chain y Logistica'],
            [324, 'Gerente Depto. Atencion Tec. Territorial'],
            [325, 'Gerente Depto. Canales Directos'],
            [326, 'Gerente Depto. Costumer Care'],
            [327, 'Gerente Depto. de Proyectos'],
            [328, 'Gerente Depto. Facturación'],
            [329, 'Gerente Depto. Gestion de Servicios Integrales'],
            [330, 'Gerente Depto. Gestion Servicio Data Center'],
            [331, 'Gerente Depto. Marketing Corporativo'],
            [332, 'Gerente Depto. Mercado Consumidores'],
            [333, 'Gerente Depto. Mercado Hogar'],
            [334, 'Gerente Depto. Operacion Clientes y Procesos'],
            [335, 'Gerente Depto. Planificacion Financiera Y Control De Gestion'],
            [336, 'Gerente Depto. Planificación Y Control D'],
            [337, 'Gerente Depto. Planificacion y Control De Gestion'],
            [338, 'Gerente Depto. Planificación Y Gestión'],
            [339, 'Gerente Depto. Servicio A Clientes'],
            [340, 'Gerente Depto. Terminales'],
            [341, 'Gerente Depto.Ventas Segmento Industria y Comercio'],
            [342, 'Gerente Dpto Gestion Inmobiliaria'],
            [343, 'Gerente Dpto Operacion y Mantenimiento Redes de Acceso'],
            [344, 'Gerente Dpto. Aseguramiento de Calidad y NOC'],
            [345, 'Gerente Dpto. O&M Redes Core, Transporte y Plataformas'],
            [346, 'Gerente Dpto. Productos TELCO'],
            [347, 'Gerente Dpto. Provision Servicios'],
            [348, 'Gerente Dpto. Proyectos de Red'],
            [349, 'Gerente Dpto.Serv.Continuidad Operacional TI'],
            [350, 'Gerente Minsal'],
            [351, 'Gestor de Contratos Y Accesos'],
            [352, 'Gestor de Incidencias'],
            [353, 'Gestor Procesos'],
            [354, 'Grte. Depto. Segmento, Finanzas y Servs.'],
            [355, 'Grte. Dpto. Productos TI'],
            [356, 'Ing. Aseguramiento Técnico De Ingresos'],
            [357, 'Ingeniero Administracion de Redes'],
            [358, 'Ingeniero Administracion Tecnica'],
            [359, 'Ingeniero Administracion Tecnica Proyectos de Red'],
            [360, 'Ingeniero Analisis Operacional Noc'],
            [361, 'Ingeniero Atencion Servicios Redes'],
            [362, 'Ingeniero Auditoria de Proyectos'],
            [363, 'Ingeniero Calidad De Red'],
            [364, 'Ingeniero Civil Ambiental'],
            [365, 'Ingeniero Civil Bioquímica'],
            [366, 'Ingeniero Civil Eléctrica'],
            [367, 'Ingeniero Civil Electrónica'],
            [368, 'Ingeniero Civil en Computación e Informática'],
            [369, 'Ingeniero Civil en Minas'],
            [370, 'Ingeniero Civil en Obras Civiles'],
            [371, 'Ingeniero Civil Industrial'],
            [372, 'Ingeniero Civil Mecánica'],
            [373, 'Ingeniero Civil Metalúrgica'],
            [374, 'Ingeniero Civil Química'],
            [375, 'Ingeniero Civil, plan común y licenciatura en Ciencias de la Ingeniería'],
            [376, 'Ingeniero Comercial'],
            [377, 'Ingeniero Control de Gestion'],
            [378, 'Ingeniero Control Operativo Senior'],
            [379, 'Ingeniero Control Presupuesto y Contrato'],
            [380, 'Ingeniero de Aseguramiento De Ingresos'],
            [381, 'Ingeniero de Centro De Monitoreo'],
            [382, 'Ingeniero de Compras'],
            [383, 'Ingeniero de Control De Gestion Senior'],
            [384, 'Ingeniero de Control Gestion'],
            [385, 'Ingeniero de Detalles In Building'],
            [386, 'Ingeniero de Estudios y Gestion de Calidad'],
            [387, 'Ingeniero de Estudios y Gestion de Calidad Senior'],
            [388, 'Ingeniero de Gestion De Contratistas'],
            [389, 'Ingeniero de Gestion de la Informacion'],
            [390, 'Ingeniero de Gestion de Permisos'],
            [391, 'Ingeniero de Gestión De Tráficos'],
            [392, 'Ingeniero de Gestion De Traficos Senior'],
            [393, 'Ingeniero de Gestion Y Atencion Clientes Ti'],
            [394, 'Ingeniero de Gestion y Materializacion de Acuerdos'],
            [395, 'Ingeniero de Interconexión'],
            [396, 'Ingeniero de Operaciones de Gestion'],
            [397, 'Ingeniero de Operaciones de Redes Senior'],
            [398, 'Ingeniero de Operaciones Financieras'],
            [399, 'Ingeniero de Operaciones Senior'],
            [400, 'Ingeniero de Operaciones Servicio al Cliente'],
            [401, 'Ingeniero de Operaciones TI de Operacion'],
            [402, 'Ingeniero De Preventa'],
            [403, 'Ingeniero de Preventa Senior'],
            [404, 'Ingeniero de Preventa Ti'],
            [405, 'Ingeniero de Preventas Tecnica'],
            [406, 'Ingeniero de Procesos'],
            [407, 'Ingeniero de Procesos de Costeo Corporativo'],
            [408, 'Ingeniero de Procesos Operacionales'],
            [409, 'Ingeniero de Productos'],
            [410, 'Ingeniero de Productos TTPP'],
            [411, 'Ingeniero de Propuestas'],
            [412, 'Ingeniero de Proyecto a Clientes'],
            [413, 'Ingeniero de Proyecto a Clientes de Gestion'],
            [414, 'Ingeniero de Proyecto Energia y Clima'],
            [415, 'Ingeniero de Proyectos de Gestion'],
            [416, 'Ingeniero de Proyectos Ejecucion Directa'],
            [417, 'Ingeniero de Proyectos Euc'],
            [418, 'Ingeniero de Proyectos Mns'],
            [419, 'Ingeniero de Proyectos PMO'],
            [420, 'Ingeniero de Proyectos Senior'],
            [421, 'Ingeniero de Proyectos Senior de Proyecto'],
            [422, 'Ingeniero de Proyectos Servicio Clientes'],
            [423, 'Ingeniero de Regulación'],
            [424, 'Ingeniero de Seguridad SOC'],
            [425, 'Ingeniero De Sistemas'],
            [426, 'Ingeniero de Tarifas'],
            [427, 'Ingeniero de Up Selling'],
            [428, 'Ingeniero de Ventas Canal'],
            [429, 'Ingeniero Diseño de Soluciones'],
            [430, 'Ingeniero Diseño Ran'],
            [431, 'Ingeniero Eficiencia Energetica y Control de Consumos'],
            [432, 'Ingeniero en administracion de empresas'],
            [433, 'Ingeniero en Alimentos'],
            [434, 'Ingeniero en Automatización, Instrumentación y Control'],
            [435, 'Ingeniero en Biotecnología y Bioingeniería'],
            [436, 'Ingeniero en Comercio Exterior'],
            [437, 'Ingeniero en Computación e Informática'],
            [438, 'Ingeniero en Construcción'],
            [439, 'Ingeniero en Control de Gestión'],
            [440, 'Ingeniero en Electricidad'],
            [441, 'Ingeniero en Electrónica'],
            [442, 'Ingeniero en Geomensura y Cartografía'],
            [443, 'Ingeniero en gestion publica'],
            [444, 'Ingeniero en Logística'],
            [445, 'Ingeniero en Matemática y Estadística'],
            [446, 'Ingeniero en Medio Ambiente'],
            [447, 'Ingeniero en Minas y Metalurgia'],
            [448, 'Ingeniero en Prevención de Riesgos'],
            [449, 'Ingeniero en Química'],
            [450, 'Ingeniero en Recursos Humanos'],
            [451, 'Ingeniero en Recursos Renovables'],
            [452, 'Ingeniero Especialista en Respaldo'],
            [453, 'Ingeniero Especialista Ms'],
            [454, 'Ingeniero Especialista Proyecto'],
            [455, 'Ingeniero Especialista Unix'],
            [456, 'Ingeniero Especialista Virtualizacion'],
            [457, 'Ingeniero Estudios'],
            [458, 'Ingeniero Estudios Administracion Filiales'],
            [459, 'Ingeniero Estudios Evaluacion Economica Senior'],
            [460, 'Ingeniero Estudios Innovacion y Cultura'],
            [461, 'Ingeniero Estudios Nuevos Negocios'],
            [462, 'Ingeniero Estudios Senior'],
            [463, 'Ingeniero Evolucion Tecnologica'],
            [464, 'Ingeniero Forestal'],
            [465, 'Ingeniero Gestion Canales'],
            [466, 'Ingeniero Gestion de La Informacion Senior'],
            [467, 'Ingeniero Gestion de Servicio Redes'],
            [468, 'Ingeniero Gestion de Servicios'],
            [469, 'Ingeniero Gestion Operacional'],
            [470, 'Ingeniero Gestión Operativa'],
            [471, 'Ingeniero Gestion Senior'],
            [472, 'Ingeniero Gestion Venta'],
            [473, 'Ingeniero Industrial'],
            [474, 'Ingeniero Inventario de Red'],
            [475, 'Ingeniero Liquidaciones Internacionales'],
            [476, 'Ingeniero Mantencion Electrica'],
            [477, 'Ingeniero Mantencion Mecanica'],
            [478, 'Ingeniero Mantenimiento De Redes'],
            [479, 'Ingeniero Marina y Marítimo Portuaria'],
            [480, 'Ingeniero Mecánica'],
            [481, 'Ingeniero Mediciones De Calidad'],
            [482, 'Ingeniero Noc'],
            [483, 'Ingeniero Nuevas Tecnologias RAN'],
            [484, 'Ingeniero Operación De Redes'],
            [485, 'Ingeniero Operaciones'],
            [486, 'Ingeniero Operaciones Ran'],
            [487, 'Ingeniero Operaciones TI'],
            [488, 'Ingeniero Optimizacion RAN'],
            [489, 'Ingeniero Planificacion Comercial De Redes'],
            [490, 'Ingeniero Planificacion De Redes'],
            [491, 'Ingeniero Planificacion de Redes Senior'],
            [492, 'Ingeniero Planificación Y Control'],
            [493, 'Ingeniero Planificacion y Control Senior'],
            [494, 'Ingeniero Producto Datos Moviles'],
            [495, 'Ingeniero Producto Voz y Vas'],
            [496, 'Ingeniero Productos Portal, Voz e Internet SAT'],
            [497, 'Ingeniero Productos Productividad'],
            [498, 'Ingeniero Proyectos'],
            [499, 'Ingeniero Proyectos Civiles'],
            [500, 'Ingeniero Proyectos De Redes'],
            [501, 'Ingeniero Proyectos de Redes Senior'],
            [502, 'Ingeniero Proyectos de Transmision'],
            [503, 'Ingeniero Proyectos Menores'],
            [504, 'Ingeniero Senior Control de Gestion'],
            [505, 'Ingeniero Senior de Detalle Red Fija'],
            [506, 'Ingeniero Senior de Estructura de Sistema de Energia y AA'],
            [507, 'Ingeniero Senior Equipamiento Activo'],
            [508, 'Ingeniero Senior Gestion Continuidad de Negocios'],
            [509, 'Ingeniero Senior Gestion de Informacion'],
            [510, 'Ingeniero Senior Gestion de Servicios'],
            [511, 'Ingeniero Senior OOCC y Canalizacion'],
            [512, 'Ingeniero Senior Planificacion y Reporte Financiero'],
            [513, 'Ingeniero Senior Proyectos Ejecucion Directa'],
            [514, 'Ingeniero Soporte RAN'],
            [515, 'Ingeniero Soporte Ti'],
            [516, 'Jefe (A) Area Requerimientos Judiciales'],
            [517, 'Jefe Area Adm. Contratos Inmobiliarios y Gestion de Accesos'],
            [518, 'Jefe Area Administracion Tecnica De Redes'],
            [519, 'Jefe Area Administrativa'],
            [520, 'Jefe Area Alianzas Fidelizacion'],
            [521, 'Jefe Area Analisis e Informesde Calidad'],
            [522, 'Jefe Area Analisis Operacional NOC'],
            [523, 'Jefe Area Aseguramiento de Calidad'],
            [524, 'Jefe Area Aseguramiento Ingresos Procesos Tecnicos'],
            [525, 'Jefe Area Atencion Grandes Empresas'],
            [526, 'Jefe Area Atencion Servicios Redes'],
            [527, 'Jefe Area Base de Datos'],
            [528, 'Jefe Area Cambios y Configuracion Servicios TI'],
            [529, 'Jefe Area Comercio Exterior'],
            [530, 'Jefe Area Comunicacion y Soporte PEC'],
            [531, 'Jefe Area Configuracion de Red y Servicios'],
            [532, 'Jefe Area Control de Calidad'],
            [533, 'Jefe Area Control de Provision'],
            [534, 'Jefe Area Control Riesgo Operacional'],
            [535, 'Jefe Area Control Y Calidad De Procesos'],
            [536, 'Jefe Area Coordinacion Regional'],
            [537, 'Jefe Area Datos'],
            [538, 'Jefe Area de Productos Telefonos Publicos'],
            [539, 'Jefe Area Direccion de Desarrollo'],
            [540, 'Jefe Area DMR'],
            [541, 'Jefe Area Especialistas Proyectos y Homologaciones'],
            [542, 'Jefe Area Estudios'],
            [543, 'Jefe Area Facturación De 3Os y R. Share'],
            [544, 'Jefe Area Formacion y Comunicaciones del PEC'],
            [545, 'Jefe Area Front'],
            [546, 'Jefe Area Gestion Administrativa'],
            [547, 'Jefe Area Gestion Calidad'],
            [548, 'Jefe Area Gestion Custodia y Valores'],
            [549, 'Jefe Area Gestion De Incentivos y Comisiones'],
            [550, 'Jefe Area Gestion Servicios Redes'],
            [551, 'Jefe Area Gestion Trafico Mayoristas Internacionales'],
            [552, 'Jefe Area Implementacion P&S Facturacion'],
            [553, 'Jefe Area Ingenieria Conectividad Sitios Nuevos'],
            [554, 'Jefe Area Ingenieria Plataformas Red Core'],
            [555, 'Jefe Area Ingenieria Redes Backhaul y Acceso'],
            [556, 'Jefe Area Ingenieria Redes Core y Agregacion Datos'],
            [557, 'Jefe Area Ingenieria Redes Planta Externa'],
            [558, 'Jefe Area Ingenieria Servicios Red Core'],
            [559, 'Jefe Area Innov. Convergencia Fijo-Movil'],
            [560, 'Jefe Area Integral Servicios Al Cliente'],
            [561, 'Jefe Area IP/MPLS'],
            [562, 'Jefe Area Logistica'],
            [563, 'Jefe Area Mantencion y Operacion Red Planta Externa'],
            [564, 'Jefe Area Mediciones de Calidad RAN'],
            [565, 'Jefe Area Monitoreo'],
            [566, 'Jefe Area MVNO'],
            [567, 'Jefe Area Negocio Roaming'],
            [568, 'Jefe Area Noc Red de Servicios'],
            [569, 'Jefe Area Operacion Servicio Basico de Voz'],
            [570, 'Jefe Area Operacion Servicios de Voz Internacional'],
            [571, 'Jefe Area Operacion y Mantencion Mecanica'],
            [572, 'Jefe Area Operacion y Mantenimiento Core MPLS/IP'],
            [573, 'Jefe Area Operacion y Mantenimiento de Redes Core Transporte'],
            [574, 'Jefe Area Operacion y Mantenimiento Packet Core'],
            [575, 'Jefe Area Operaciones'],
            [576, 'Jefe Área Planificación y Control de Gestion'],
            [577, 'Jefe Area Planificacion y Gestion Financiera'],
            [578, 'Jefe Area Procesos'],
            [579, 'Jefe Area Proyecto Operacionales y Mejora Continua'],
            [580, 'Jefe Area Proyectos'],
            [581, 'Jefe Area Proyectos de Innovacion'],
            [582, 'Jefe Area Proyectos MVNO'],
            [583, 'Jefe Area Red Transporte y Acceso'],
            [584, 'Jefe Area Red TV/Satelital'],
            [585, 'Jefe Area Redes Core y Agregacion Transporte'],
            [586, 'Jefe Area Servicios TI'],
            [587, 'Jefe Area Soporte Servicios Fijos y Preventa'],
            [588, 'Jefe Area Tecnica'],
            [589, 'Jefe Area Terminales'],
            [590, 'Jefe Concesiones y Espectro'],
            [591, 'Jefe de Area Administracion De Servicios'],
            [592, 'Jefe de Área Administración De Sistemas'],
            [593, 'Jefe de Area Administracion De Sistemas Tools'],
            [594, 'Jefe de Area Administracion y Gestion EPCM'],
            [595, 'Jefe de Área Adquisición De Sitios'],
            [596, 'Jefe de Area Ampliaciones In-Building'],
            [597, 'Jefe de Área Aseguramiento Técnico De In'],
            [598, 'Jefe de Área Atención Clientes Preferenc'],
            [599, 'Jefe de Area Atencion Clientes Roaming'],
            [600, 'Jefe de Area Atencion Grandes Cuentas'],
            [601, 'Jefe de Área Calidad Canales Y Procesos'],
            [602, 'Jefe de Area Calidad Proyectos de Red'],
            [603, 'Jefe de Area Centro De Comando'],
            [604, 'Jefe de Área Club Fidelización'],
            [605, 'Jefe de Area Compras Infraestructura Redes y Data Center'],
            [606, 'Jefe de Área Compras Internas'],
            [607, 'Jefe de Area Compras Proyectos'],
            [608, 'Jefe de Area Compras Proyectos Especiales'],
            [609, 'Jefe de Área Compras Vas & Ti'],
            [610, 'Jefe de Area Control De Gestion'],
            [611, 'Jefe de Área Control De Gestión Comercia'],
            [612, 'Jefe de Area Control Ingreso de Negocio y Fraude'],
            [613, 'Jefe de Área Control Operativo'],
            [614, 'Jefe de Area Control Proceso Tasacion'],
            [615, 'Jefe de Área Coordinacion Tecnica de Proyectos'],
            [616, 'Jefe de Area Cuenta Corriente'],
            [617, 'Jefe de Area CVM Gestion Canales'],
            [618, 'Jefe de Area CVM Planificacion'],
            [619, 'Jefe de Area CVM Postpago'],
            [620, 'Jefe de Area CVM Prepago'],
            [621, 'Jefe de Área De Gestión de Tráficos Naci'],
            [622, 'Jefe de Area de Marketing'],
            [623, 'Jefe de Area De Procesos Operacionales'],
            [624, 'Jefe de Área De Supply Chain'],
            [625, 'Jefe de Area Desarrollo de Plataformas'],
            [626, 'Jefe de Area Desarrollo de Productos'],
            [627, 'Jefe de Area Diseño Indoor'],
            [628, 'Jefe de Área Distribución Facturación'],
            [629, 'Jefe de Área Ejecución Ran'],
            [630, 'Jefe de Area Especialistas Svs Telco'],
            [631, 'Jefe de Area Especialistas Ti'],
            [632, 'Jefe de Área Estudios'],
            [633, 'Jefe de Area Estudios De Mercado'],
            [634, 'Jefe de Área Experiencia De Clientes'],
            [635, 'Jefe de Area Facturacion Clientes Empresas y Corporaciones'],
            [636, 'Jefe de Area Formacion Canales'],
            [637, 'Jefe de Area Front Empresa Movil'],
            [638, 'Jefe de Area Gestion de Contratistas'],
            [639, 'Jefe de Area Gestion de Cositing y Zonas Saturadas'],
            [640, 'Jefe de Área Gestión De Egresos'],
            [641, 'Jefe de Área Gestión De Ingresos y Egres'],
            [642, 'Jefe de Área Gestión De La Información'],
            [643, 'Jefe de Área Gestión De Opex'],
            [644, 'Jefe de Área Gestión De Servicios'],
            [645, 'Jefe de Area Gestion Operacional'],
            [646, 'Jefe de Área Gestión Operativa'],
            [647, 'Jefe de Area Gestion Performance'],
            [648, 'Jefe de Area Gestion Reclamos'],
            [649, 'Jefe de Area Gestion Servicios Datacenter'],
            [650, 'Jefe de Area Gestion Sg Calidad'],
            [651, 'Jefe de Area Gestión Slm y Contratos'],
            [652, 'Jefe de Área Gestión Ventas Remotas Móvil'],
            [653, 'Jefe De Area Gestion Y Planificacion'],
            [654, 'Jefe de Area Hogar'],
            [655, 'Jefe de Area Implementacion Productos y Servicios'],
            [656, 'Jefe de Area Ingenieria Estructural'],
            [657, 'Jefe de Area Ingenieria Proyectos Especiales'],
            [658, 'Jefe de Area Inteligencia De Negocios'],
            [659, 'Jefe de Area Inteligencia Inmobiliaria'],
            [660, 'Jefe de Área Inteligencia Segmento Grand'],
            [661, 'Jefe de Area Interconexion Red Fija'],
            [662, 'Jefe de Área Interconexión Red Móvil'],
            [663, 'Jefe de Área Inventario'],
            [664, 'Jefe de Area Marketing Intelligence'],
            [665, 'Jefe de Área Marketing Online'],
            [666, 'Jefe de Área Marketing Personas'],
            [667, 'Jefe de Área Medios Corporativo'],
            [668, 'Jefe de Area Negocios Moviles'],
            [669, 'Jefe de Area Normativa y Gestion'],
            [670, 'Jefe de Area Operación Cobranza Empresas'],
            [671, 'Jefe de Area Operacion Compras'],
            [672, 'Jefe de Area Operacion IVR y USSD'],
            [673, 'Jefe de Area Operacion Tecnica Chile'],
            [674, 'Jefe de Área Operaciones Dc'],
            [675, 'Jefe de Área Operaciones Mediación Y Tar'],
            [676, 'Jefe de Área Operaciones Plataformas'],
            [677, 'Jefe de Área Operaciones Servicios Vas'],
            [678, 'Jefe de Area Optimizacion RAN'],
            [679, 'Jefe de Area Optimizacion y Reclamos'],
            [680, 'Jefe de Area Permisos Obras Civiles'],
            [681, 'Jefe de Area Planficacion Demanda'],
            [682, 'Jefe de Area Planificacion Comercial Despliegue de Redes'],
            [683, 'Jefe de Area Planificacion Crecimiento Infraestructura'],
            [684, 'Jefe de Area Planificacion de Servicios'],
            [685, 'Jefe de Area Planificacion Red Core'],
            [686, 'Jefe de Área Planificación Red De Acceso'],
            [687, 'Jefe de Área Plataforma Comercial Y Proc'],
            [688, 'Jefe de Área Plataformas De Atención'],
            [689, 'Jefe de Area Plataformas Vas'],
            [690, 'Jefe de Área Post Venta Terminales'],
            [691, 'Jefe de Area Procesos Operacionales'],
            [692, 'Jefe de Area Procesos y Calidad'],
            [693, 'Jefe de Area Productos y Servicios'],
            [694, 'Jefe de Area Provision Mayoristas'],
            [695, 'Jefe de Area Proyecto Operacionales'],
            [696, 'Jefe De Area Proyecto SAC'],
            [697, 'Jefe de Area Proyectos A Clientes'],
            [698, 'Jefe de Area Proyectos de Automatizacion'],
            [699, 'Jefe de Area Proyectos Masivos RAN'],
            [700, 'Jefe de Area Proyectos TI'],
            [701, 'Jefe de Area Proyectos Transmision'],
            [702, 'Jefe de Area RAN Macro'],
            [703, 'Jefe de Área Roaming'],
            [704, 'Jefe de Area Soporte Comercial'],
            [705, 'Jefe de Área Soporte Ran'],
            [706, 'Jefe de Area Soporte y Mejora Continua'],
            [707, 'Jefe de Area Sopote a la Provision'],
            [708, 'Jefe de Area Storage'],
            [709, 'Jefe de Area Tarifas'],
            [710, 'Jefe De Area Tend E Innov Merc Conv'],
            [711, 'Jefe De Area Tend E Innov Mercado Masivo'],
            [712, 'Jefe de Area Tend&Innv Ti/Telco'],
            [713, 'Jefe de Auditoria de Proyectos'],
            [714, 'Jefe de Gestion Experiencia Clientes'],
            [715, 'Jefe de Inventario de Red'],
            [716, 'Jefe de Negocios I. De Pascua'],
            [717, 'Jefe de Negocios Zonal RM'],
            [718, 'Jefe de Negocios Zonal RM Rural'],
            [719, 'Jefe de Procesos'],
            [720, 'Jefe de Procesos y Metodos'],
            [721, 'Jefe de Programa'],
            [722, 'Jefe de Programacion y Control'],
            [723, 'Jefe de Proyecto Online'],
            [724, 'Jefe de Proyecto Procesos De Negocios'],
            [725, 'Jefe de Proyectos'],
            [726, 'Jefe de Proyectos de Clientes'],
            [727, 'Jefe de Proyectos de Clientes Senior'],
            [728, 'Jefe de Proyectos PMO'],
            [729, 'Jefe de Proyectos Senior'],
            [730, 'Jefe de Proyectos Senior PMO'],
            [731, 'Jefe de Riesgos Transaccionales y Procesos'],
            [732, 'Jefe de Tienda'],
            [733, 'Jefe de Tienda A'],
            [734, 'Jefe de Tienda VIP'],
            [735, 'Jefe de Turno Noc'],
            [736, 'Jefe de Ventas Canales Masivos Santiago'],
            [737, 'Jefe de Ventas Canales Masivos Sur'],
            [738, 'Jefe Estrategia y Estudios Regulatorios'],
            [739, 'Jefe Productos Entel Visa'],
            [740, 'Jefe Productos Mayoristas'],
            [741, 'Jefe Proyecto Planificacion Inventario'],
            [742, 'Jefe Proyectos de Clientes'],
            [743, 'Jefe Segmento Online'],
            [744, 'Jefe(A) Area Trade Marketing'],
            [745, 'Jefe(A) Area Imagen Corporativa'],
            [746, 'Jefe(A) de Area Evaluacion De Proyectos'],
            [747, 'Jefe(A) de Área Programacion Y Control'],
            [748, 'Jefe(A) de Negocios Empresas'],
            [749, 'Jefe(A) de Negocios Zonal'],
            [750, 'Jefe(A) Desarrollo Empresas'],
            [751, 'Jefe(A) Operac. Comerciales'],
            [752, 'KAM'],
            [753, 'Kam Agentes Especializados'],
            [754, 'Kam Canales Masivos'],
            [755, 'KAM Desarrollo'],
            [756, 'KAM MID'],
            [757, 'KAM Senior'],
            [758, 'Kinesiologo(a)'],
            [759, 'Licenciado en Letras y Literatura'],
            [760, 'Licenciado en Química'],
            [761, 'Lider Administracion Base de Datos'],
            [762, 'Lider Cobranza Empresas Externas'],
            [763, 'Lider de Cuenta Corriente'],
            [764, 'Lider de Operacion de Svs Al Cliente'],
            [765, 'Lider de Operacion Facturacion Personas'],
            [766, 'Lider de PMO'],
            [767, 'Lider de Proyecto Logistica'],
            [768, 'Lider de Proyecto Logistica Redes e Infraestructura'],
            [769, 'Lider de Proyecto Riesgo Persona'],
            [770, 'Lider de Proyectos'],
            [771, 'Lider de Zona'],
            [772, 'Lider Gestion de Contratos'],
            [773, 'Lider Gestion Operacional'],
            [774, 'Lider Gestion Servicios Y Atencion Clientes Ti'],
            [775, 'Lider Operacion Facturacion Empresas'],
            [776, 'Lider Operación Facturación Serv. Tercer'],
            [777, 'Lider Tecnico Servicio al Cliente'],
            [778, 'Lincenciatura en Artes'],
            [779, 'Logopeda'],
            [780, 'Market Manager'],
            [781, 'Market Manager Grandes Empresas'],
            [782, 'Market Manager Prepago'],
            [783, 'Market Manager Suscripcion'],
            [784, 'Market Manager Terminales Suscripcion'],
            [785, 'Matemáticas y/o Estadísticas'],
            [786, 'Matrona'],
            [787, 'Medicina'],
            [788, 'Medicina Veterinaria'],
            [789, 'Médico'],
            [790, 'Músico, Canto o Danza'],
            [791, 'Nutrición y Dietética'],
            [792, 'Nutricionista'],
            [793, 'Obstetricia y Puericultura'],
            [794, 'Odontologo'],
            [795, 'Odontólogo'],
            [796, 'Operador'],
            [797, 'Operador Basis Sap'],
            [798, 'Operador Centro De Comando'],
            [799, 'Operador Centro Monitoreo'],
            [800, 'Operador Data Center'],
            [801, 'Operador de Monitoreo'],
            [802, 'Operador Ti'],
            [803, 'Óptico y optometrista'],
            [804, 'otro'],
            [805, 'Pedagogía en Artes y Música'],
            [806, 'Pedagogía en Ciencias'],
            [807, 'Pedagogía en Educación Básica'],
            [808, 'Pedagogía en Educación de Párvulos'],
            [809, 'Pedagogía en Educación Diferencial'],
            [810, 'Pedagogía en Educación Física'],
            [811, 'Pedagogía en Filosofía y Religión'],
            [812, 'Pedagogía en Historia, Geografía y Ciencias Sociales'],
            [813, 'Pedagogía en Idiomas'],
            [814, 'Pedagogía en Lenguaje, Comunicación y/o Castellano'],
            [815, 'Pedagogía en Matemáticas y Computación'],
            [816, 'Periodista'],
            [817, 'Podólogo'],
            [818, 'Product Manager'],
            [819, 'Product Manager Acceso Multiservicio e Internet'],
            [820, 'Product Manager M2M'],
            [821, 'Product Manager Marca Propia'],
            [822, 'Product Manager Reacondicionados'],
            [823, 'Product Manager Roaming'],
            [824, 'Product Manager Sim Card Y Homologacion'],
            [825, 'Product Manager Televisión'],
            [826, 'Product Manager Terminales BAM y Hogar'],
            [827, 'Product Manager Vas Ld'],
            [828, 'Profesor de educacion general basica'],
            [829, 'Psicologo'],
            [830, 'Psicólogo'],
            [831, 'Psicopedagoga(o)'],
            [832, 'Publicista'],
            [833, 'Química Industrial'],
            [834, 'Química y Farmacia'],
            [835, 'Quimico'],
            [836, 'Químico Ambiental'],
            [837, 'Realizador de Cine y Televisión'],
            [838, 'Recaudador (a)'],
            [839, 'Recepcionista'],
            [840, 'Relaciondor(a) Pública'],
            [841, 'Secretaria'],
            [842, 'Senior Market Manager'],
            [843, 'Senior Product Manager'],
            [844, 'Service Manager'],
            [845, 'Sociologo'],
            [846, 'Soporte Atención Clientes'],
            [847, 'Soporte Comercial'],
            [848, 'Soporte Comercial Y Administrativo'],
            [849, 'Soporte Tecnico'],
            [850, 'Subg. Proyectos Canales e Implementacion Productos y Serv.'],
            [851, 'Subg.Proy.Telco Wan,Mov y Convergentes'],
            [852, 'Subgerente Operaciones Financieras'],
            [853, 'Subgerente Adaptacion de Sitios y Soluciones de Camuflaje'],
            [854, 'Subgerente Adm. de Recursos para Provisión Servicios'],
            [855, 'Subgerente Administracion de Proyectos CORE'],
            [856, 'Subgerente Administracion de Sistemas'],
            [857, 'Subgerente Administracion Plataforma Operacionales Ti'],
            [858, 'Subgerente Alianzas E Innovacion'],
            [859, 'Subgerente Ampliacion De Sitios RAN'],
            [860, 'Subgerente Ampliacion Infraestructura de Red'],
            [861, 'Subgerente Ampliacion Red MAC y Transmision'],
            [862, 'Subgerente Analisis De Mercado Y Plan'],
            [863, 'Subgerente Atencion de Problemas y Servicios'],
            [864, 'Subgerente Atencion Grandes Empresas'],
            [865, 'Subgerente Atenciones Automaticas'],
            [866, 'Subgerente Calidad de Interacciones  y Procesos'],
            [867, 'Subgerente Calidad De Red'],
            [868, 'Subgerente Calidad Facturacion y Administracion Clientes'],
            [869, 'Subgerente Canal Online Empresa'],
            [870, 'Subgerente Canal Tiendas'],
            [871, 'Subgerente Centro Comando Operac.Terreno'],
            [872, 'Subgerente Com.Corp. y Relaciones Inst.'],
            [873, 'Subgerente Compras Infraestructura'],
            [874, 'Subgerente Compras Tecnicas'],
            [875, 'Subgerente Contabilidad Activo Fijo'],
            [876, 'Subgerente Control de Gestion'],
            [877, 'Subgerente Control de Operaciones'],
            [878, 'Subgerente Control Fraude Y Riesgo Proce'],
            [879, 'Subgerente Control Gestion Servicios Ti'],
            [880, 'Subgerente Control Y Analisis Gestion'],
            [881, 'Subgerente Coordinacion Tec. de Proyecto'],
            [882, 'Subgerente Crm Austral'],
            [883, 'Subgerente Crm Centro Norte'],
            [884, 'Subgerente Crm Centro Sur'],
            [885, 'Subgerente Crm Metropolitano'],
            [886, 'Subgerente Crm Norte'],
            [887, 'Subgerente Crm Sur'],
            [888, 'Subgerente de Administracion Financiera'],
            [889, 'Subgerente de Aseguramiento de Ingresos'],
            [890, 'Subgerente de Busquedas y Adquisicion de Sitios'],
            [891, 'Subgerente de Canal'],
            [892, 'Subgerente de Cobranzas'],
            [893, 'Subgerente De Compras Comerciales'],
            [894, 'Subgerente de Contabilidad'],
            [895, 'Subgerente de Contabilidad Filiales'],
            [896, 'Subgerente De Control De Gestion'],
            [897, 'Subgerente de Control y Calidad TI'],
            [898, 'Subgerente de Control y Gestion T Y O'],
            [899, 'Subgerente de Customer Value Mag'],
            [900, 'Subgerente de Ejecucion de Proyecto Despliegue Red'],
            [901, 'Subgerente de Estrategia De Servicio'],
            [902, 'Subgerente de Estructuras, Sistemas de energia y AA'],
            [903, 'Subgerente de Evaluacion Economica'],
            [904, 'Subgerente de Gestion y Experiencia de Cliente'],
            [905, 'Subgerente de Informacion de Gestion'],
            [906, 'Subgerente de Ingenieria de Sistemas'],
            [907, 'Subgerente De Marketing'],
            [908, 'Subgerente de Medio de Pago'],
            [909, 'Subgerente de Operaciones TI'],
            [910, 'Subgerente de PMO TI'],
            [911, 'Subgerente de Procesos'],
            [912, 'Subgerente de Procesos y Metodos'],
            [913, 'Subgerente de Productos Convergentes'],
            [914, 'Subgerente De Productos De Conectividad'],
            [915, 'Subgerente de Proyectos Inmobiliarios'],
            [916, 'Subgerente de Recaudacion'],
            [917, 'Subgerente de Regulación'],
            [918, 'Subgerente de Roaming'],
            [919, 'Subgerente De Servicios Distribuidos'],
            [920, 'Subgerente de Soporte Comercial'],
            [921, 'Subgerente de Ventas Canal Agentes Espec'],
            [922, 'Subgerente de Ventas Canal Directo Móvil'],
            [923, 'Subgerente De Ventas Canal Directo Santiago'],
            [924, 'Subgerente de Ventas Canales Masivos'],
            [925, 'Subgerente Desarrollo de Contratistas y Normas'],
            [926, 'Subgerente Desarrollo de Productos'],
            [927, 'Subgerente Desarrollo E Innovación'],
            [928, 'Subgerente Desarrollo I-Factory'],
            [929, 'Subgerente Desarrollo Mercado'],
            [930, 'Subgerente Desarrollo Productos  Ti'],
            [931, 'Subgerente Eventos, Auspicios Y Club'],
            [932, 'Subgerente Evolucion Tecnologica de Red'],
            [933, 'Subgerente Excelencia Operacional'],
            [934, 'Subgerente Experiencia E Inteligencia De'],
            [935, 'Subgerente Explotacion y Continuidad SVS     '],
            [936, 'Subgerente Fiscalizacion Y Reportes Externos'],
            [937, 'Subgerente Gestion Clientes Servicios Telco'],
            [938, 'Subgerente Gestion Clintes y Nivel de SVS'],
            [939, 'Subgerente Gestion De Egresos'],
            [940, 'Subgerente Gestión De Información'],
            [941, 'Subgerente Gestion Operacion Ventas'],
            [942, 'Subgerente Grandes Proyectos a Clientes'],
            [943, 'Subgerente Implementacion Nuevos Productos'],
            [944, 'Subgerente Ingeneria Ti'],
            [945, 'Subgerente Ingenieria Core Datos, Transporte y Agregacion'],
            [946, 'Subgerente Ingenieria Diseño RAN'],
            [947, 'Subgerente Ingenieria Optimizacion Ran'],
            [948, 'Subgerente Ingenieria Planta Externa, Backhaul y Acceso'],
            [949, 'Subgerente Ingenieria Plataformas VAS y Soporte de Red'],
            [950, 'Subgerente Iniciativas Estrategicas'],
            [951, 'Subgerente Integral De Servicios Al Cliente'],
            [952, 'Subgerente Interconexión'],
            [953, 'Subgerente Larga Distancia'],
            [954, 'Subgerente Liquidaciones Internacionales'],
            [955, 'Subgerente Marketing Y Productos'],
            [956, 'Subgerente Medicion y Tarificacion De Trafico Mayoristas'],
            [957, 'Subgerente Mercado Grandes Empresas'],
            [958, 'Subgerente Mercado Terminales'],
            [959, 'Subgerente Negocios De Trafico'],
            [960, 'Subgerente Noc'],
            [961, 'Subgerente Nuevos Negocios'],
            [962, 'Subgerente Nuevos Productos'],
            [963, 'Subgerente Op. y Mantenimento Redes Core Datos y Transporte'],
            [964, 'Subgerente Op. y Mantenimiento Redes de Backhaul y Acceso'],
            [965, 'Subgerente Op.Concepcion-Temuco'],
            [966, 'Subgerente Operacion de Desarrollo y Gestion'],
            [967, 'Subgerente Operación De Svs Zona Norte'],
            [968, 'Subgerente Operacion Facturacion Empresas Corp.'],
            [969, 'Subgerente Operacion Regional Santiago'],
            [970, 'Subgerente Operación Y Calidad Facturaci'],
            [971, 'Subgerente Operacion y Explotacion Serv.'],
            [972, 'Subgerente Operacion y Mantenimiento Core Servicio de Voz'],
            [973, 'Subgerente Operacion y Mantenimiento Planta Externa'],
            [974, 'Subgerente Operacion y Mantenimiento RAN'],
            [975, 'Subgerente Operacion y Mantenimiento VAS y Plataformas'],
            [976, 'Subgerente Operacion Y Mejora Continua'],
            [977, 'Subgerente Operaciones De Svs Centro'],
            [978, 'Subgerente Operaciones De Svs Sur'],
            [979, 'Subgerente Operaciones De Svs V Región'],
            [980, 'Subgerente Operaciones Grandes Clientes'],
            [981, 'Subgerente Planificacion Analisis De Costos'],
            [982, 'Subgerente Planificación De Red'],
            [983, 'Subgerente Planificacion Operacional'],
            [984, 'Subgerente Planificacion Y Control De Gest Term'],
            [985, 'Subgerente Planificacion y Control de la Provision'],
            [986, 'Subgerente Planificacion Y Gestion Comercial'],
            [987, 'Subgerente Planificacion y Optimizacion'],
            [988, 'Subgerente Planificacion Y Reporte Financiero'],
            [989, 'Subgerente PMO'],
            [990, 'Subgerente Post Venta Terminales'],
            [991, 'Subgerente Procesos De Negocios'],
            [992, 'Subgerente Procesos Y PMO'],
            [993, 'Subgerente Producto Datos'],
            [994, 'Subgerente Producto Terminales'],
            [995, 'Subgerente Productos Datacenter'],
            [996, 'Subgerente Productos Telco'],
            [997, 'Subgerente Provisión De Servicios'],
            [998, 'Subgerente Proyectos A Clientes'],
            [999, 'Subgerente Proyectos Estrategicos de Redes'],
            [1000, 'Subgerente Proyectos Ti'],
            [1001, 'Subgerente Riesgo Continuidad De Negocio'],
            [1002, 'Subgerente Riesgo Credito'],
            [1003, 'Subgerente RSE y Asuntos Publicos'],
            [1004, 'Subgerente Seguros Corporativos'],
            [1005, 'Subgerente Soporte A La Provision'],
            [1006, 'Subgerente Soporte Mayoristas y Proyectos Especiales'],
            [1007, 'Subgerente Soporte Ti'],
            [1008, 'Subgerente Soporte y Estandarizacion Pro'],
            [1009, 'Subgerente Supply Chain'],
            [1010, 'Subgerente Telefonia Movil'],
            [1011, 'Subgerente Tendecia E Innovacion'],
            [1012, 'Subgerente Trade Marketing'],
            [1013, 'Subgerente Usuarios Lideres'],
            [1014, 'Subgerente Ventas Empresas Santiago'],
            [1015, 'Subgerente Ventas Mayoristas'],
            [1016, 'Supervisor (A) Control Room'],
            [1017, 'Supervisor (A) Operaciones Externas'],
            [1018, 'Supervisor (A) Operaciones Remotas'],
            [1019, 'Supervisor Administracion de Servicios'],
            [1020, 'Supervisor Administracion De Sistemas'],
            [1021, 'Supervisor Administrativo'],
            [1022, 'Supervisor Asistencia De Gerencia'],
            [1023, 'Supervisor Centro de Comando'],
            [1024, 'Supervisor Centro De Monitoreo De Svs'],
            [1025, 'Supervisor Cobranza Empresas'],
            [1026, 'Supervisor Compras Tecnicas'],
            [1027, 'Supervisor Comunicaciones Clientes Integrales'],
            [1028, 'Supervisor Data Center'],
            [1029, 'Supervisor de Bodega'],
            [1030, 'Supervisor de Cobranza Masiva'],
            [1031, 'Supervisor de Cobranzas'],
            [1032, 'Supervisor de Gestion de Permisos'],
            [1033, 'Supervisor de Laboratorio'],
            [1034, 'Supervisor de Servicios Generales'],
            [1035, 'Supervisor de Sistemas Core y Datos'],
            [1036, 'Supervisor De Soporte Usuarios'],
            [1037, 'Supervisor de Terreno'],
            [1038, 'Supervisor Explotacion De Sistemas'],
            [1039, 'Supervisor Gestion de Inventarios y Reestudios'],
            [1040, 'Supervisor Gestion De Seguros'],
            [1041, 'Supervisor Gestion Reclamos Facturacion'],
            [1042, 'Supervisor Operación y Mantención Inmobiliaria'],
            [1043, 'Supervisor Operaciones Servicio Al Cliente'],
            [1044, 'Supervisor Proyectos de Instalaciones'],
            [1045, 'Supervisor Recaudación Externa'],
            [1046, 'Supervisor Recaudación Interna'],
            [1047, 'Supervisor Soporte Servicios'],
            [1048, 'Supervisor Soporte Ventas Fijo'],
            [1049, 'Supervisor Tecnico'],
            [1050, 'Supervisor Tecnico Servicio Al Cliente'],
            [1051, 'Supervisor(A) Atencion Pyme'],
            [1052, 'Supervisor(A) De Captura Pyme'],
            [1053, 'Supervisor(A) De Desarrollo Pyme'],
            [1054, 'Supervisor(A) Front'],
            [1055, 'Supervisor(A) Requerimientos Judiciales'],
            [1056, 'Team Leader'],
            [1057, 'Team Leader Caja'],
            [1058, 'Team Leader Cajero Comercial'],
            [1059, 'Tecnico Administrador De Redes'],
            [1060, 'Tecnico Analista Centro monitoreo de Svs'],
            [1061, 'Técnico Asistente del Educador de Párvulos'],
            [1062, 'Tecnico Centro De Comando'],
            [1063, 'Tecnico de Laboratorio'],
            [1064, 'Tecnico de Operaciones Servicio al Cliente'],
            [1065, 'Tecnico De Provision De Svs'],
            [1066, 'Tecnico de Proyectos a Clientes'],
            [1067, 'Tecnico de Sistemas'],
            [1068, 'Tecnico de Terreno Senior'],
            [1069, 'Técnico en Administración de Empresas'],
            [1070, 'Técnico en Alimentos'],
            [1071, 'Técnico en Computación e Informática'],
            [1072, 'Técnico en Construcción y Obras Civiles'],
            [1073, 'Técnico en Contabilidad General'],
            [1074, 'Técnico en Deporte, Recreación y Preparación Física'],
            [1075, 'Técnico en Electricidad y Electricidad Industrial'],
            [1076, 'Técnico en Enfermería'],
            [1077, 'Técnico en Mantenimiento Industrial'],
            [1078, 'Técnico en Mecánica Automotriz'],
            [1079, 'Técnico en Mecánica Industrial'],
            [1080, 'Técnico en Minería y Metalurgia'],
            [1081, 'Tecnico en Prevencion de Riego'],
            [1082, 'Técnico en Prevención de Riesgos'],
            [1083, 'Técnico en Química (Análisis e Industrial)'],
            [1084, 'Tecnico Gestion De Traficos'],
            [1085, 'Técnico Gestión Operativa'],
            [1086, 'Técnico Mantención Eléctrica'],
            [1087, 'Tecnico Mantencion Mecanica'],
            [1088, 'Tecnico Mantenimiento De Redes'],
            [1089, 'Técnico Mediciones de Calidad'],
            [1090, 'Tecnico Monitor Batch'],
            [1091, 'Tecnico Noc'],
            [1092, 'Tecnico Operacion de Redes'],
            [1093, 'Tecnico Operador Centro De Monitoreo Svs'],
            [1094, 'Tecnico Profesional'],
            [1095, 'Técnico Sala de Equipos'],
            [1096, 'Tecnico Senior Sistemas'],
            [1097, 'Tecnico Servicio Al Cliente'],
            [1098, 'Tecnico Soporte a la Provision'],
            [1099, 'Técnico Soporte Usuarios'],
            [1100, 'Tecnico Terreno'],
            [1101, 'Tecnología Médica'],
            [1102, 'Terapia Ocupacional'],
            [1103, 'Trabajador Social'],
            [1104, 'Trade Marketer'],
            [1105, 'Traductor e Interprete'],
            [1106, 'Veterinario'],
        ];
        $profesiones = array_map(function($profesion) use ($now) {
           return [
               'id' => $profesion[0],
               'profesion' => $profesion[1],
               'updated_at' => $now,
               'created_at' => $now,
           ];
        }, $profesiones);
        \DB::table('profesiones')->insert($profesiones);

        $afps = [
            [1,'AFP Provida'],
            [2,'AFP Cuprum'],
            [3,'APF PLANVITAL'],
            [4,'AFP CAPITAL'],
            [5,'AFP HABITAT'],
            [6,'AFP MODELO'],
        ];
        $afps = array_map(function($afp) use ($now) {
           return [
               'id' => $afp[0],
               'afp' => $afp[1],
               'updated_at' => $now,
               'created_at' => $now,
           ];
        }, $afps);
        \DB::table('afps')->insert($afps);

        $isapres = [
            [1,'Isapre Banmédica.'],
            [2,'Isapre Consalud.'],
            [3,'Isapre Colmena.'],
            [4,'Isapre CruzBlanca.'],
            [5,'Isapre Nueva Masvida.'],
            [6,'Isapre Vida Tres.'],
            [7,'Fonasa.'],
        ];
        $isapres = array_map(function($isapre) use ($now) {
           return [
               'id' => $isapre[0],
               'isapre' => $isapre[1],
               'updated_at' => $now,
               'created_at' => $now,
           ];
        }, $isapres);
        \DB::table('isapres')->insert($isapres);
/*
        $industria = [
            [1,'Administración'],
            [2,'Call center'],
            [3,'Comercio exterior'],
            [4,'Comunicación'],
            [5,'Construcción'],
            [6,'Diseño'],
            [7,'Educación'],
            [8,'Finanzas'],
            [9,'Gastronomía'],
            [10,'Gerencia'],
            [11,'Ingeniería'],
            [12,'Legales'],
            [13,'Logística'],
            [14,'Marketing'],
            [15,'Minería'],
            [16,'Oficios'],
            [17,'Producción'],
            [18,'Recursos humanos'],
            [19,'Salud'],
            [20,'Secretaria'],
            [21,'Seguros'],
            [22,'Tecnología'],
            [23,'Ventas'],
        ];
*/
        $industria = [
            [1,'Administración pública'],
            [2,'Aduana / Agencia de aduanas'],
            [3,'Aérea'],
            [4,'Aeronaves'],
            [5,'AFP / AFP'],
            [6,'Agro-Industrial'],
            [7,'Agropecuaria'],
            [8,'Agua/obras sanitarias'],
            [9,'Alimenticia'],
            [10,'Alquiler y arriendo general'],
            [11,'Ambiental'],
            [12,'Arquitectura'],
            [13,'Artesanal'],
            [14,'Automotriz'],
            [15,'Banca/Financiera'],
            [16,'Bebidas'],
            [17,'Biotecnología'],
            [18,'Boutique'],
            [19,'Capacitación'],
            [20,'Carpintería / Muebles'],
            [21,'Celulosa'],
            [22,'Científica'],
            [23,'Comercio'],
            [24,'Comercio electrónico'],
            [25,'Comercio Exterior'],
            [26,'Comercio Mayorista'],
            [27,'Comercio Minorista'],
            [28,'Confecciones'],
            [29,'Construcción'],
            [30,'Consultoría'],
            [31,'Consumo masivo'],
            [32,'Correos y envíos postales'],
            [33,'Cultura'],
            [34,'Decoración'],
            [35,'Defensa'],
            [36,'Deportes'],
            [37,'Diseño'],
            [38,'Distribuidora'],
            [39,'Editorial'],
            [40,'Educación'],
            [41,'Electricidad'],
            [42,'Electrónica'],
            [43,'Electrónica de consumo'],
            [44,'Energía'],
            [45,'Entretenimiento'],
            [46,'Exportación/Importación'],
            [47,'Farmacéutica'],
            [48,'Ferroviaria'],
            [49,'Financiera'],
            [50,'Forestal'],
            [51,'Ganadería'],
            [52,'Gastronomía'],
            [53,'Gobierno'],
            [54,'Higiene y Perfumería'],
            [55,'Holding'],
            [56,'Hotelería'],
            [57,'Imprenta'],
            [58,'Industria pesquera / acuícola'],
            [59,'Industrial'],
            [60,'Información e investigación'],
            [61,'Informática / tecnología'],
            [62,'Ingeniería'],
            [63,'Inmobiliaria'],
            [64,'Internet'],
            [65,'Inversiones'],
            [66,'Jurídica'],
            [67,'Laboratorio'],
            [68,'Logística/distribución'],
            [69,'Manufactura'],
            [70,'Maquinarias y equipos'],
            [71,'Medicina / Salud'],
            [72,'Medios de comunicación'],
            [73,'Metalmecánica'],
            [74,'Minería'],
            [75,'Naviera'],
            [76,'Notarías'],
            [77,'ONGs'],
            [78,'Óptica'],
            [79,'Otra'],
            [80,'Papelera'],
            [81,'Peluquerías y salones de belleza'],
            [82,'Pesca'],
            [83,'Petróleo/Gas/Combustible'],
            [84,'Petroquímica'],
            [85,'Plásticos'],
            [86,'Poder ejecutivo'],
            [87,'Poder judicial'],
            [88,'Poder legislativo'],
            [89,'Productora'],
            [90,'Productora de cine y tv'],
            [91,'Publicidad /Marketing'],
            [92,'Química'],
            [93,'Recursos humanos'],
            [94,'Restaurantes / Casinos'],
            [95,'Retail'],
            [96,'RRPP'],
            [97,'Seguridad'],
            [98,'Seguros'],
            [99,'Servicios de salud'],
            [100,'Servicios domésticos'],
            [101,'Servicios financieros'],
            [102,'Servicios funerarios'],
            [103,'Servicios Generales'],
            [104,'Siderurgia / metalurgia'],
            [105,'Supermercado / Hipermercado'],
            [106,'Tabacalera'],
            [107,'Tecnologías de información'],
            [108,'Telecomunicaciones'],
            [109,'Textil'],
            [110,'Transporte'],
            [111,'Turismo'],
            [112,'Veterinaria'],
            [113,'Vidrios y envases'],
        ];
        $industria = array_map(function($ind) use ($now) {
           return [
               'id' => $ind[0],
               'industria' => $ind[1],
               'updated_at' => $now,
               'created_at' => $now,
           ];
        }, $industria);
        \DB::table('industria')->insert($industria);
    }
}
